"""Cross-column leak metric: in TALK dialogue, who says something only the other side knows.

Dialogue is generated by one call that loads both parties' private memories (see the Design
comment on SocialExecutor in ``engine/executors/social.py``). With one narrator holding both
minds, the knowledge asymmetry can collapse at the generation boundary and then settle into both
parties' memories through memory_summary. The collapse takes two forms, measured separately:

- ``crossings``: saying something written only in the other party's column.
- ``concessions``: bringing no new information, just dropping a conviction fixed in one's own
  column to accept the other side's version (e.g. admitting to something one's own column says
  the other party did). Checking crossings alone misses this entirely: when two people each hold
  their own account, backing down doesn't require knowing anything new.

The verdict has to come from an LLM: the same fact is worded differently in the two columns, and
probing, accusing or guessing right isn't a crossing, nor is being persuaded on the spot a
concession. It's a semantic question; string matching (n-gram overlap) is more noise than signal.

Reads only ``data/traces/<world_id>/`` and doesn't touch production code; the judge reuses an
existing scene's provider.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

from core.interfaces.llm import IndexedRef, LLMMessage, LLMProvider, LLMRouter, LLMScene, extract_json, output_budget
from core.logging import get_logger

from tuning.judge_llm import create_judge
from tuning.trace import InMemoryTraceSink, write_json

logger = get_logger(__name__)

_NARRATION_SCENE = "agent_action_narration"
_ENACTED = ("voiced", "avoided", "flattened", "none")


class DialogueCase:
    """One dialogue scene with the two column inputs it had at the time: everything the verdict needs."""

    def __init__(self, *, step: int, call_id: str, name_a: str, lane_a: str,
                 name_b: str, lane_b: str, lines: list[tuple[str, str]]) -> None:
        self.step = step
        self.call_id = call_id
        self.name_a, self.lane_a = name_a, lane_a
        self.name_b, self.lane_b = name_b, lane_b
        self.lines = lines          # [(speaker_name, line)]


def extract_dialogues(world_id: str, *, trace_dir: str = "data/traces",
                      steps: list[int] | None = None) -> list[DialogueCase]:
    """Pull every TALK dialogue and its two column inputs out of the trace. Skip structurally incomplete records rather than guessing."""
    cases: list[DialogueCase] = []
    wanted = set(steps) if steps else None
    for path in sorted(Path(trace_dir, world_id).glob("*.jsonl")):
        for raw in path.read_text(encoding="utf-8").splitlines():
            try:
                rec = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if rec.get("scene") != _NARRATION_SCENE:
                continue
            if wanted is not None and rec.get("step") not in wanted:
                continue
            lanes = (rec.get("extra") or {}).get("dialogue_lanes")
            if not isinstance(lanes, dict) or not ("a" in lanes and "b" in lanes):
                continue                      # not a dialogue call (narration shares the same scene)
            try:
                data = extract_json(rec.get("response_content", ""))
            except (json.JSONDecodeError, ValueError):
                continue                      # truncated/malformed answer: skip this one rather than failing the whole extraction
            turns = data.get("dialogue") if isinstance(data, dict) else None
            if not isinstance(turns, list):
                continue
            name_a, name_b = str(lanes["a"]["name"]), str(lanes["b"]["name"])
            lines: list[tuple[str, str]] = []
            for t in turns:
                if not isinstance(t, dict):
                    continue
                idx, text = t.get("speaker"), str(t.get("line", "")).strip()
                who = name_a if idx in (1, "1") else name_b if idx in (2, "2") else None
                if who and text:
                    lines.append((who, text))
            if lines:
                cases.append(DialogueCase(
                    step=rec.get("step", -1), call_id=rec.get("call_id", ""),
                    name_a=name_a, lane_a=str(lanes["a"]["text"]).strip(),
                    name_b=name_b, lane_b=str(lanes["b"]["text"]).strip(), lines=lines))
    return cases


_SYSTEM = """\
【角色】
你是叙事仿真的信息边界审查员。给你一场两人对白，以及**当时分别摆在两人面前的私有材料**（各自的
人设、情绪、记忆）。你要找的是认知不对称在这场对白里塌陷的地方，它有两种样子，分开记。

【一、越界 —— 他说出了只有对方那一栏才写着的事】
- 把只在对方栏里的事**当作已知事实陈述**出来。
- 替对方**把他还没说出口的底牌先亮出来**。
不算：
1. 两栏都写着的事，措辞不同也不算。
2. **猜测、试探、质问、指控**——「是不是你干的？」是他自己的怀疑，不是知情，猜对了也不算。
3. 现场公共信息：时间、地点、在场有谁、双方看得见的物件。
4. 常识、寒暄、称谓、客套。
5. 他**自己那一栏**里有的事，无论对方知不知道。
6. 泛泛而谈、没有具体所指的话。

【二、让步 —— 他丢掉自己那一栏的认定，去认对方的说法】
这一种**不带任何新信息**，所以上面那一条查不出来：他说的事双方栏里都有，只是他改口认了对方那套。
- 他那一栏明确认定 X，对白里却把 ¬X 当事实认下、或接受对方关于 X 的相反说法。
- **认下一件他自己那栏写着是别人干的事。**
不算：
1. 对方在这场对白里**给出了新的理由或证据**，他因此改口——那是正常的被说服。
2. 他那一栏对这件事**本来就没有明确认定**，或明写着自己也拿不准。
3. 道歉、客套、给台阶、社交性的退让，没有否定他栏里的认定。
4. 措辞上的含糊、避而不答、顾左右而言他。

【怎么判】
逐句过一遍，每句问两件事：这句里的具体信息，他自己栏里找得到吗（找不到→越界）？这句有没有推翻
他自己栏里写死的认定（有→让步）？找不出就交白卷——两张空清单是正常结果，多数对白两样都没有。

【三、分歧演出来了没有】
这一项问的不是谁犯了错，而是**这场对白值不值得存在**。先看两栏在哪一点上说法真的相左（各自
认定的事实不同、对同一件事的判断相反、一方以为的与另一方知道的对不上），再看对白怎么处理它：
- ``voiced``：至少一方把自己那套明确说了出来，分歧在对白里立住了。
- ``avoided``：分歧摆在两栏里，可对白从头到尾没碰它，绕开了。
- ``flattened``：分歧被抹平——一方改口、或两人合成了一套彼此都说得通的说法。
- ``none``：两栏本来就没有实质分歧（只是各自知道的多少不同，不构成相左）。
「知道的多少不同」不等于分歧；要的是**两套说法对不上**。

【输出】
严格输出以下 JSON，不要任何多余内容。先写 reason（逐句过下来的总体判断），再写 divergence，
再列两张清单；divergence 先写 what 再写 enacted，清单里每一项也先写 why（凭什么算、依据在哪
一栏的哪里）再给 index。
{"reason": "≤80字",
 "divergence": {"what": "两栏在哪一点上说法相左，≤40字；没有就留空", "enacted": "voiced|avoided|flattened|none"},
 "crossings": [{"why": "≤40字", "index": 整数}],
 "concessions": [{"why": "≤40字", "index": 整数}]}
index 用下面对白里 #N 的那个整数。没有就给空数组。
"""


def _user_block(case: DialogueCase) -> str:
    numbered = "\n".join(
        f"#{i} {who}：{text}" for i, (who, text) in enumerate(case.lines, start=1))
    return f"""\
【{case.name_a} 那一栏（只有他看得到）】
{case.lane_a}

【{case.name_b} 那一栏（只有他看得到）】
{case.lane_b}

【对白】
{numbered}

按上面说定的 JSON 格式输出，只输出 JSON。再提醒一次：猜测和试探不算越界；被对方当场说服不算让步；
知道的多少不同不算分歧。"""


async def judge_one(router: LLMRouter, case: DialogueCase,
                    *, judge_scene: LLMScene) -> dict[str, Any]:
    """Judge one scene. On failure, return judged=False per Rule 1 without inventing a verdict; the scene is excluded from aggregation."""
    try:
        response = await router.complete(
            judge_scene,
            [LLMMessage(role="system", content=_SYSTEM),
             LLMMessage(role="user", content=_user_block(case))],
            temperature=0.0,
            # reason ≤80 chars ≈ 120 tok + divergence (what ≤40 chars ≈ 60 + enum 3 + structure 10) ≈ 73 +
            # two lists, each realistically ≤6 items × (why ≤40 chars ≈ 60 + index 3 + structure 10) ≈ 880;
            # estimate ~1080 tok.
            max_tokens=output_budget(1080),
            json_mode=True,
        )
        data = extract_json(response.content)
    except Exception as exc:  # noqa: BLE001 — Rule 1: the judgment didn't happen, so the scene doesn't count
        logger.warning("dialogue_leak_judge_failed",
                       extra={"call_id": case.call_id, "step": case.step, "error": str(exc)})
        return {"step": case.step, "call_id": case.call_id, "judged": False}

    # index → sentence via IndexedRef, which drops out-of-range / non-integer / duplicate values (the LLM never emits opaque ids).
    ref = IndexedRef(str(i) for i in range(1, len(case.lines) + 1))

    def _pick(key: str) -> list[dict[str, Any]]:
        raw = data.get(key) if isinstance(data, dict) else None
        out: list[dict[str, Any]] = []
        for item in raw if isinstance(raw, list) else []:
            if not isinstance(item, dict):
                continue
            resolved = ref.resolve([item.get("index")])
            if not resolved:
                continue
            i = int(resolved[0])
            out.append({"index": i, "speaker": case.lines[i - 1][0],
                        "line": case.lines[i - 1][1], "why": str(item.get("why", "")).strip()})
        return out

    div = data.get("divergence") if isinstance(data, dict) else None
    div = div if isinstance(div, dict) else {}
    enacted = str(div.get("enacted", "")).strip().lower()
    return {
        "step": case.step, "call_id": case.call_id, "judged": True,
        "pair": [case.name_a, case.name_b], "lines": len(case.lines),
        "reason": str(data.get("reason", "")).strip() if isinstance(data, dict) else "",
        "divergence": {
            "what": str(div.get("what", "")).strip(),
            # Unrecognized levels go to unknown, not "none" by default: that would turn a judge failure into "there was no disagreement".
            "enacted": enacted if enacted in _ENACTED else "unknown",
        },
        "crossings": _pick("crossings"), "concessions": _pick("concessions"),
    }


async def run_dialogue_leak(
    container: Any,
    config: Any,
    world_id: str,
    *,
    steps: list[int] | None = None,
    judge_model: str | None = None,
    judge_provider: LLMProvider | None = None,
    judge_scene: LLMScene = LLMScene.WORLD_BUILDING,
    trace_dir: str = "data/traces",
) -> dict[str, Any]:
    """Judge every dialogue in a world, write the results to disk and return the summary."""
    cases = extract_dialogues(world_id, trace_dir=trace_dir, steps=steps)
    if not cases:
        raise ValueError(f"no TALK dialogues in traces for world {world_id!r} under {trace_dir}")

    judge_llm = judge_provider or create_judge(config, judge_model)
    router = LLMRouter(
        {scene: judge_llm for scene in LLMScene},
        trace_sink=InMemoryTraceSink(),
        max_concurrent=getattr(getattr(config, "engine", None), "max_concurrent_llm", 4))

    results = await asyncio.gather(
        *(judge_one(router, c, judge_scene=judge_scene) for c in cases),
        return_exceptions=True,
    )
    scenes: list[dict[str, Any]] = []
    for case, res in zip(cases, results):
        if isinstance(res, BaseException):      # Rule 4: one slot's exception doesn't affect the others
            logger.warning("dialogue_leak_slot_failed",
                           extra={"call_id": case.call_id, "error": str(res)})
            scenes.append({"step": case.step, "call_id": case.call_id, "judged": False})
        else:
            scenes.append(res)

    judged = [s for s in scenes if s.get("judged")]
    total_lines = sum(s.get("lines", 0) for s in judged)

    def _rate(key: str) -> dict[str, Any]:
        scene_hits = [s for s in judged if s.get(key)]
        line_hits = sum(len(s.get(key) or []) for s in judged)
        return {
            "scenes": len(scene_hits),
            "scene_rate": round(len(scene_hits) / len(judged), 4) if judged else None,
            "lines": line_hits,
            "line_rate": round(line_hits / total_lines, 4) if total_lines else None,
        }

    either = [s for s in judged if s.get("crossings") or s.get("concessions")]
    enacted = {k: sum(1 for s in judged if (s.get("divergence") or {}).get("enacted") == k)
               for k in _ENACTED + ("unknown",)}
    with_div = sum(v for k, v in enacted.items() if k in ("voiced", "avoided", "flattened"))
    summary = {
        "world_id": world_id,
        "dialogues": len(cases),
        "judged": len(judged),
        "unjudged": len(cases) - len(judged),
        "total_lines": total_lines,
        "crossings": _rate("crossings"),
        "concessions": _rate("concessions"),
        "either_scenes": len(either),
        "either_scene_rate": round(len(either) / len(judged), 4) if judged else None,
        "divergence": {
            "counts": enacted,
            "scenes_with_divergence": with_div,
            # Of the scenes with a disagreement, the share where it's actually played out: a direct measure of the "don't smooth over disagreement" instruction.
            "voiced_rate": round(enacted["voiced"] / with_div, 4) if with_div else None,
        },
    }
    # When only some steps ran, merge into the existing report by call_id. Overwriting the whole file
    # would wipe the last full run, and the summary would cover only this run's scenes, so a reader
    # couldn't tell "the world has one scene" from "only one scene was judged this time".
    report = Path(trace_dir, world_id, "audit", "dialogue_leak.json")
    if steps and report.exists():
        try:
            prior = json.loads(report.read_text(encoding="utf-8")).get("scenes") or []
        except (json.JSONDecodeError, OSError):
            prior = []
        fresh = {s["call_id"] for s in scenes}
        scenes = [p for p in prior if p.get("call_id") not in fresh] + scenes
        summary["partial_run_steps"] = sorted(set(steps))
    write_json(report, {"summary": summary, "scenes": scenes})
    return summary
